### ISSUE TITLE
Building unicode-property-aliases-ecmascript... requires unicode-property-aliasas-ecmascript!?

### ISSUE THREAD

**Issue by SnarkBoojum** [mathiasbynens/unicode-property-aliases-ecmascript#1]
Would it be possible to provide a bootstrapping version?

I wanted to package this for Debian, but of course having a package depend on itself is a problem. If I remove all mention of canonicalProperties in scripts/build.js, I do get an index.js, but it has everything in data/PropertyAliases.txt, which isn't the case of the index.js you ship.

I guess there is a reason for not going the most direct way, but the fact that it makes things non-bootstrapping is quite annoying.

Thanks,

Snark on #debian-js

**Comment by SnarkBoojum** [comment]
Oh, sorry, there's alias and there's names -- I hadn't seen!

**Comment by mathiasbynens** [comment]
No worries :)
